import { motion } from 'framer-motion';

export default function ExecutiveSummaryCard({ summary }) {
  if (!summary) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4 }}
      className="bg-white border border-slate-200/60 rounded-[16px] p-6 shadow-sm space-y-4"
    >
      {/* Header */}
      <div className="flex items-center gap-3">
        <span className="w-8 h-8 bg-indigo-50 border border-indigo-100/50 rounded-xl flex items-center justify-center text-sm flex-shrink-0">
          💡
        </span>
        <div>
          <h3 className="text-sm font-bold text-slate-800">AI Executive Summary</h3>
          <p className="text-[10px] text-slate-400">Generated by Gemini — Plain English overview</p>
        </div>
      </div>

      {/* Summary Text */}
      <div className="p-4 bg-indigo-50/40 border border-indigo-100/50 rounded-xl">
        <p className="text-[13px] text-slate-700 leading-relaxed font-medium">
          {summary}
        </p>
      </div>
    </motion.div>
  );
}
